name: grizzly_array
description: Named 1D and 2D arrays for scientific computing and data analysis.
version: 0.5.0-dev
homepage: https://github.com/Grizzly-dart/grizzly_array

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  grizzly_primitives: ^2.0.2
  collection: ^1.15.0
  text_table: ^2.6.0
  grizzly_range: ^3.0.0

dev_dependencies:
  test: ^1.20.1

dependency_overrides:
  grizzly_primitives:
    path: ../grizzly_primitives