name: grizzly_array
description: Named 1D and 2D arrays for scientific computing and data analysis.
version: 0.5.0-dev
homepage: https://github.com/Grizzly-dart/grizzly_array
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  grizzly_primitives: ^2.0.2
  grizzly_series:
  collection: ^1.14.12
  text_table: ^2.6.0
  grizzly_range:

dev_dependencies:
  test: ^1.14.3

dependency_overrides:
  grizzly_primitives:
    path: ../grizzly_primitives
  grizzly_series:
    path: ../grizzly_series